name: "Reporte de Vulnerabilidad"
description: "Usa este formulario para reportar vulnerabilidades de forma responsable."
title: "Título breve de la vulnerabilidad"
labels: ["security"]
assignees:
  - security-team

body:
  - type: markdown
    attributes:
      value: |
        **IMPORTANTE:** No incluyas información sensible en canales públicos.
        Consulta nuestra [Política de Seguridad](https://github.com/kkokotero/boxels/blob/main/SECURITY.md) para más detalles.

  - type: input
    id: reporter_name
    attributes:
      label: "Investigador / Reportante"
      description: "Nombre o alias. Opcional si deseas permanecer anónimo."
      placeholder: "Ej: Juan Pérez / CyberWolf"
    validations:
      required: false

  - type: input
    id: discovery_date
    attributes:
      label: "Fecha de descubrimiento"
      description: "Formato AAAA-MM-DD"
      placeholder: "2025-08-06"
    validations:
      required: true

  - type: input
    id: affected_versions
    attributes:
      label: "Versión afectada"
      description: "Indica la versión exacta o rango de versiones."
      placeholder: "v2.3.1 o >=2.0.0 <2.3.2"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: "Entorno donde se detectó"
      options:
        - Producción
        - Desarrollo
        - Pruebas / Local
        - Otro
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: "Resumen breve"
      description: "Describe en 1-3 líneas en qué consiste el problema."
      placeholder: "Ej: La API de autenticación permite ejecución remota de código..."
    validations:
      required: true

  - type: textarea
    id: technical_details
    attributes:
      label: "Detalles técnicos"
      description: "Describe el problema y por qué es una vulnerabilidad."
      placeholder: "Explicación técnica..."
    validations:
      required: true

  - type: dropdown
    id: attack_vector
    attributes:
      label: "Vector de ataque"
      options:
        - Local
        - Remoto
        - Físico
        - Otro
    validations:
      required: true

  - type: input
    id: cvss
    attributes:
      label: "Severidad estimada (CVSS v3.1)"
      description: "Opcional. Ej: 9.8 (Crítica)"
      placeholder: "Ej: 7.5 (Alta)"
    validations:
      required: false

  - type: textarea
    id: reproduction_steps
    attributes:
      label: "Pasos para reproducir"
      description: "Describe paso a paso cómo reproducir la vulnerabilidad."
      placeholder: |
        1. Ir a...
        2. Ejecutar...
        3. Resultado esperado / real...
    validations:
      required: true

  - type: textarea
    id: proof_of_concept
    attributes:
      label: "Evidencias / Pruebas de Concepto"
      description: "Capturas, logs, requests HTTP, scripts de prueba, etc."
      placeholder: "Adjuntar pruebas aquí..."
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: "Impacto potencial"
      description: "Explica qué podría pasar si la vulnerabilidad no se corrige."
      placeholder: "Ej: Acceso no autorizado a datos sensibles..."
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: "Mitigación propuesta (opcional)"
      description: "Sugerencias para resolver o reducir el riesgo."
      placeholder: "Ej: Implementar validación de entrada..."
    validations:
      required: false

  - type: checkboxes
    id: confirmation
    attributes:
      label: "Confirmación"
      description: "Marca para confirmar que aceptas la política."
      options:
        - label: "Confirmo que este reporte es original."
          required: true
        - label: "Acepto que Boxels gestione este reporte siguiendo la Política de Seguridad."
          required: true
